/* tslint:disable */
/* eslint-disable */
/**
 * AdList.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CompleteSmartTaskCommand {
    'id'?: number;
}

export const CompletionStatus = {
    Pending: 'Pending',
    Completed: 'Completed',
} as const;

export type CompletionStatus = typeof CompletionStatus[keyof typeof CompletionStatus];


export interface CreateSmartTaskCommand {
    'title'?: string | null;
    'description'?: string | null;
    'dueDate'?: string | null;
}
export interface DeleteSmartTaskCommand {
    'id'?: number;
}

export const ExceptionReasonCode = {
    InvalidRequest: 'InvalidRequest',
    UserNotFound: 'UserNotFound',
    UserEmailIsRequired: 'UserEmailIsRequired',
    TaskNotFound: 'TaskNotFound',
    TaskAlreadyCompleted: 'TaskAlreadyCompleted',
} as const;

export type ExceptionReasonCode = typeof ExceptionReasonCode[keyof typeof ExceptionReasonCode];


export interface GetSmartTaskQueryResponse {
    'id'?: number;
    'title'?: string | null;
    'description'?: string | null;
    'dueDate'?: string | null;
    'completionStatus'?: string | null;
    'authorName'?: string | null;
    'createdAt'?: string;
}
export interface GetTaskCommandResponse {
    'id'?: number;
    'title'?: string | null;
    'description'?: string | null;
    'dueDate'?: string | null;
    'completionStatus'?: string | null;
    'authorName'?: string | null;
    'createdAt'?: string;
}
export interface GetTasksCommand {
    'startIndex'?: number | null;
    'endIndex'?: number | null;
    'sorts'?: Array<SortOption> | null;
}
export interface GetTasksCommandResponse {
    'tasks'?: Array<GetTaskCommandResponse> | null;
    'totalCount'?: number;
}

export const SortDirection = {
    Asc: 'Asc',
    Desc: 'Desc',
} as const;

export type SortDirection = typeof SortDirection[keyof typeof SortDirection];


export interface SortOption {
    'name'?: string | null;
    'direction'?: SortDirection;
}


export interface UpdateSmartTaskCommand {
    'id'?: number;
    'title'?: string | null;
    'description'?: string | null;
    'dueDate'?: string | null;
    'completionStatus'?: CompletionStatus;
}



/**
 * AdListWebApi - axios parameter creator
 */
export const AdListWebApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CompleteSmartTaskCommand} completeSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeTaskPut: async (completeSmartTaskCommand: CompleteSmartTaskCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'completeSmartTaskCommand' is not null or undefined
            assertParamExists('completeTaskPut', 'completeSmartTaskCommand', completeSmartTaskCommand)
            const localVarPath = `/complete-task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(completeSmartTaskCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateSmartTaskCommand} createSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTaskPost: async (createSmartTaskCommand: CreateSmartTaskCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSmartTaskCommand' is not null or undefined
            assertParamExists('createTaskPost', 'createSmartTaskCommand', createSmartTaskCommand)
            const localVarPath = `/create-task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSmartTaskCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteSmartTaskCommand} deleteSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTaskDelete: async (deleteSmartTaskCommand: DeleteSmartTaskCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteSmartTaskCommand' is not null or undefined
            assertParamExists('deleteTaskDelete', 'deleteSmartTaskCommand', deleteSmartTaskCommand)
            const localVarPath = `/delete-task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteSmartTaskCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/get-task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {GetTasksCommand} getTasksCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTasksPost: async (getTasksCommand: GetTasksCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getTasksCommand' is not null or undefined
            assertParamExists('getTasksPost', 'getTasksCommand', getTasksCommand)
            const localVarPath = `/get-tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getTasksCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateSmartTaskCommand} updateSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaskPut: async (updateSmartTaskCommand: UpdateSmartTaskCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateSmartTaskCommand' is not null or undefined
            assertParamExists('updateTaskPut', 'updateSmartTaskCommand', updateSmartTaskCommand)
            const localVarPath = `/update-task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSmartTaskCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdListWebApi - functional programming interface
 */
export const AdListWebApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdListWebApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CompleteSmartTaskCommand} completeSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async completeTaskPut(completeSmartTaskCommand: CompleteSmartTaskCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.completeTaskPut(completeSmartTaskCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdListWebApi.completeTaskPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateSmartTaskCommand} createSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTaskPost(createSmartTaskCommand: CreateSmartTaskCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTaskPost(createSmartTaskCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdListWebApi.createTaskPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteSmartTaskCommand} deleteSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTaskDelete(deleteSmartTaskCommand: DeleteSmartTaskCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTaskDelete(deleteSmartTaskCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdListWebApi.deleteTaskDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSmartTaskQueryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTaskGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdListWebApi.getTaskGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {GetTasksCommand} getTasksCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTasksPost(getTasksCommand: GetTasksCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTasksCommandResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTasksPost(getTasksCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdListWebApi.getTasksPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateSmartTaskCommand} updateSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTaskPut(updateSmartTaskCommand: UpdateSmartTaskCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTaskPut(updateSmartTaskCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdListWebApi.updateTaskPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdListWebApi - factory interface
 */
export const AdListWebApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdListWebApiFp(configuration)
    return {
        /**
         * 
         * @param {CompleteSmartTaskCommand} completeSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeTaskPut(completeSmartTaskCommand: CompleteSmartTaskCommand, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.completeTaskPut(completeSmartTaskCommand, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateSmartTaskCommand} createSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTaskPost(createSmartTaskCommand: CreateSmartTaskCommand, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.createTaskPost(createSmartTaskCommand, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteSmartTaskCommand} deleteSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTaskDelete(deleteSmartTaskCommand: DeleteSmartTaskCommand, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteTaskDelete(deleteSmartTaskCommand, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskGet(options?: RawAxiosRequestConfig): AxiosPromise<GetSmartTaskQueryResponse> {
            return localVarFp.getTaskGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GetTasksCommand} getTasksCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTasksPost(getTasksCommand: GetTasksCommand, options?: RawAxiosRequestConfig): AxiosPromise<GetTasksCommandResponse> {
            return localVarFp.getTasksPost(getTasksCommand, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateSmartTaskCommand} updateSmartTaskCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaskPut(updateSmartTaskCommand: UpdateSmartTaskCommand, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.updateTaskPut(updateSmartTaskCommand, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdListWebApi - object-oriented interface
 */
export class AdListWebApi extends BaseAPI {
    /**
     * 
     * @param {CompleteSmartTaskCommand} completeSmartTaskCommand 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public completeTaskPut(completeSmartTaskCommand: CompleteSmartTaskCommand, options?: RawAxiosRequestConfig) {
        return AdListWebApiFp(this.configuration).completeTaskPut(completeSmartTaskCommand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateSmartTaskCommand} createSmartTaskCommand 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTaskPost(createSmartTaskCommand: CreateSmartTaskCommand, options?: RawAxiosRequestConfig) {
        return AdListWebApiFp(this.configuration).createTaskPost(createSmartTaskCommand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteSmartTaskCommand} deleteSmartTaskCommand 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTaskDelete(deleteSmartTaskCommand: DeleteSmartTaskCommand, options?: RawAxiosRequestConfig) {
        return AdListWebApiFp(this.configuration).deleteTaskDelete(deleteSmartTaskCommand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTaskGet(options?: RawAxiosRequestConfig) {
        return AdListWebApiFp(this.configuration).getTaskGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GetTasksCommand} getTasksCommand 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTasksPost(getTasksCommand: GetTasksCommand, options?: RawAxiosRequestConfig) {
        return AdListWebApiFp(this.configuration).getTasksPost(getTasksCommand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateSmartTaskCommand} updateSmartTaskCommand 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTaskPut(updateSmartTaskCommand: UpdateSmartTaskCommand, options?: RawAxiosRequestConfig) {
        return AdListWebApiFp(this.configuration).updateTaskPut(updateSmartTaskCommand, options).then((request) => request(this.axios, this.basePath));
    }
}



